language: python

python:
  - "2.7"

before_script:
  - sudo apt-get install python-appindicator
  - sudo apt-get install python-gtk2
  - pip install mock
  - easy_install pyrg

script: ./run_tests.sh
