language: python

python:
  - "2.7"

before_script:
  - wget http://ftp.gnome.org/pub/GNOME/sources/pygtk/2.24/pygtk-2.24.0.tar.bz2
  - tar xf pygtk-2.24.0.tar.bz2
  - cd pygtk-2.24.0
  - export PKG_CONFIG_PATH=/home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION/lib/pkgconfig
  - ./configure --prefix=/home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION/
  - make
  - make install
  - cd ..
  - sudo apt-get install python-appindicator
  - pip install mock
  - easy_install pyrg

script: ./run_tests.sh
